version: '3'

networks:
    tomcat-net:
        driver: bridge
        ipam:
            config:
            -
                subnet: 172.33.0.0/16

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"
        volumes:
            - "./nginx-conf/tomcat.conf:/etc/nginx/conf.d/tomcat.conf:ro"
            - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
        logging:
            driver: journald
            options:
                tag: 'nginx'
        networks:
            tomcat-net:
                ipv4_address: 172.33.1.10
        ulimits:
            nproc: 3
            memlock: 48000

    tomcat:
        build:
            context: .
            dockerfile: tomcat.Dockerfile
        logging:
            driver: journald
            options:
                tag: 'tomcat'
        networks:
            tomcat-net:
                ipv4_address: 172.33.1.20
        ulimits:
            nproc: 20
            memlock: 48000
